version: 2
jobs:
  build:
    docker:
      - image: "circleci/node:12"
    steps:
      - checkout
      - run:
          name: install
          command: npm install
      - run:
          name: test
          command: npm run test
      - run:
          name: deploy_staging
          command: ./scripts/deploy_staging.sh
